global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecs-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pharmacare-alb-809690050.ap-southeast-2.elb.amazonaws.com:80']

  - job_name: 'cloudwatch'
    ec2_sd_configs:
      - region: ap-southeast-2
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
