from fastapi import FastAPI, HTTPException, UploadFile, File
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
import os
import pandas as pd
import io
from datetime import datetime
import difflib
import json
import uuid

# LangChain Imports
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

# Local Imports
from agent_tools import check_low_stock, forecast_demand, place_order, add_stock_to_inventory, remove_stock_from_inventory

# Load Environment Variables
load_dotenv()

app = FastAPI(title="Pharmacy Agent API")

# CORS Setup
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"], # Next.js default port
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize LLM
# Prioritize OpenAI if available, as Google Auth is currently failing
if os.getenv("OPENAI_API_KEY"):
    print("Using OpenAI...")
    llm = ChatOpenAI(model="gpt-3.5-turbo")
elif os.getenv("GOOGLE_API_KEY"):
    print("Using Google Gemini...")
    llm = ChatGoogleGenerativeAI(model="gemini-pro")
else:
    print("Warning: No API Key found. Agent will fail.")
    llm = None

# Define Tools
tools = [check_low_stock, forecast_demand, place_order, add_stock_to_inventory, remove_stock_from_inventory]

# Define Agent Prompt
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are the Pharmacy Manager for MLRIT College. You are responsible for maintaining stock levels, forecasting demand based on student needs, and ensuring procurement is efficient.\n"
               "You have access to tools to check stock, forecast demand, place orders, update inventory, and remove stock.\n"
               "Always maintain a professional, helpful, and proactive persona.\n"
               "CRITICAL INSTRUCTION: When you use a tool (like 'forecast_demand' or 'check_low_stock'), your Final Answer MUST contain the FULL details, tables, and lists returned by that tool. Do NOT summarize or omit the data. Show the user exactly what the tool found.\n"
               "If the user asks to 'reorder', use the check_low_stock tool.\n"
               "If the user asks for 'analysis' or 'forecast', use the forecast_demand tool.\n"
               "If the user wants to buy something, provide the purchase links using the place_order tool.\n"
               "AFTER the user confirms they have paid (e.g., says 'Confirmed payment'), use the add_stock_to_inventory tool to update the database.\n"
               "If the user asks to delete, remove, or discard items (e.g., 'Remove 10 Dolo'), use the remove_stock_from_inventory tool."),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
    ("placeholder", "{agent_scratchpad}"),
])

# Create Agent Executor
if llm:
    agent = create_tool_calling_agent(llm, tools, prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, return_intermediate_steps=True)
else:
    agent_executor = None

class ChatRequest(BaseModel):
    message: str
    history: list = []

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    if not agent_executor:
        raise HTTPException(status_code=500, detail="LLM not initialized. Check API Keys.")
    
    # Handle Slash/Backslash Commands
    user_input = request.message.strip()
    if user_input == "\\":
        return {"response": "### 🛠️ Available Commands\n\n*   `/analysis` - **Forecast Demand**: Analyzes sales history and weather to predict future needs.\n*   `/reorder` - **Check Stock**: Scans inventory for low stock items and suggests reorders."}
    
    # Map commands to natural language for the agent
    if user_input == "/analysis":
        user_input = "Run a demand forecast analysis."
    elif user_input == "/reorder":
        user_input = "Check for low stock items and suggest reorders."

    try:
        # Convert history to LangChain format
        chat_history = []
        for msg in request.history:
            if msg['role'] == 'user':
                chat_history.append(HumanMessage(content=msg['content']))
            elif msg['role'] == 'assistant':
                chat_history.append(AIMessage(content=msg['content']))

        response = agent_executor.invoke({
            "input": user_input,
            "chat_history": chat_history
        })
        
        final_output = response["output"]
        
        # Append tool outputs if they aren't already in the final output
        # This ensures tables and lists generated by tools are always visible to the user
        if "intermediate_steps" in response:
            for action, observation in response["intermediate_steps"]:
                if isinstance(observation, str) and len(observation) > 50:
                    # Check if the observation is already substantially present in the final output
                    # If not, prepend it (so the data comes before the summary)
                    if observation[:50] not in final_output:
                        final_output = observation + "\n\n---\n" + final_output
                        
        return {"response": final_output}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
def read_root():
    return {"status": "Pharmacy System API is running"}

@app.get("/inventory")
def get_inventory():
    from models import engine, InventoryBatch, Drug
    from sqlalchemy.orm import Session
    
    session = Session(engine)
    try:
        results = session.query(InventoryBatch, Drug).join(Drug, InventoryBatch.drug_id == Drug.drug_id).all()
        inventory = []
        for batch, drug in results:
            inventory.append({
                "drug_name": drug.brand_name,
                "generic_name": drug.generic_name,
                "batch_number": batch.batch_number,
                "quantity": batch.quantity,
                "expiry": str(batch.expiry_date),
                "location": batch.location
            })
        return inventory
    finally:
        session.close()

@app.post("/upload-inventory")
async def upload_inventory(file: UploadFile = File(...)):
    from models import engine, InventoryBatch, Drug, Supplier
    from sqlalchemy.orm import Session
    
    if not file.filename.endswith(('.xlsx', '.xls')):
        raise HTTPException(status_code=400, detail="Invalid file format. Please upload an Excel file.")
    
    contents = await file.read()
    try:
        df = pd.read_excel(io.BytesIO(contents))
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Error reading Excel file: {str(e)}")
    
    # Expected Columns: Brand Name, Batch Number, Quantity, Expiry Date, Location, Supplier Name
    required_columns = ['Brand Name', 'Batch Number', 'Quantity', 'Expiry Date']
    if not all(col in df.columns for col in required_columns):
        raise HTTPException(status_code=400, detail=f"Missing required columns. Please ensure the Excel has: {', '.join(required_columns)}")
    
    session = Session(engine)
    added_count = 0
    errors = []
    
    try:
        for index, row in df.iterrows():
            brand_name = row['Brand Name']
            batch_number = str(row['Batch Number'])
            quantity = int(row['Quantity'])
            expiry_date = pd.to_datetime(row['Expiry Date']).date()
            location = row.get('Location', 'General Storage')
            
            # Find Drug
            # 1. Exact/Case-insensitive Match
            drug = session.query(Drug).filter(Drug.brand_name.ilike(brand_name)).first()
            
            # 2. Fuzzy Match (Spelling Mistakes)
            if not drug:
                all_drugs = session.query(Drug).all()
                # Create a dictionary of {lower_case_name: DrugObject}
                drug_map = {d.brand_name.lower(): d for d in all_drugs}
                
                # Get close matches
                matches = difflib.get_close_matches(str(brand_name).lower(), drug_map.keys(), n=1, cutoff=0.6)
                
                if matches:
                    best_match = matches[0]
                    drug = drug_map[best_match]
                    errors.append(f"⚠️ Row {index+1}: Auto-corrected '{brand_name}' to '{drug.brand_name}'.")
            
            # 3. AI Lookup & Auto-Creation (New Medicine)
            if not drug and llm:
                try:
                    print(f"🔍 AI Searching for unknown drug: {brand_name}")
                    ai_prompt = f"""
                    You are a pharmaceutical expert. Identify the medicine '{brand_name}'. 
                    If it is a real medicine, return a valid JSON object with these exact keys:
                    - "is_valid": true
                    - "generic_name": "Chemical name"
                    - "category": "Category (e.g., Antibiotic, Pain Relief, Supplement, Antihistamine)"
                    - "manufacturer": "Likely manufacturer name"
                    - "requires_prescription": true/false
                    
                    If it is NOT a real medicine or you are unsure, return:
                    {{"is_valid": false}}
                    
                    Do not add any markdown formatting. Just the JSON string.
                    """
                    ai_response = llm.invoke(ai_prompt).content
                    # Clean response
                    ai_response = ai_response.replace("```json", "").replace("```", "").strip()
                    drug_info = json.loads(ai_response)
                    
                    if drug_info.get("is_valid"):
                        # Create new Drug
                        # Let DB handle drug_id (Auto Increment)
                        drug = Drug(
                            brand_name=brand_name, # Use the name from Excel
                            generic_name=drug_info['generic_name'],
                            category=drug_info['category'],
                            manufacturer=drug_info['manufacturer'],
                            requires_prescription=drug_info['requires_prescription'],
                            reorder_level=20, # Default
                            sku=f"SKU-{str(uuid.uuid4())[:8].upper()}" # Generate unique SKU
                        )
                        session.add(drug)
                        session.flush() # Flush to get the ID ready for batch
                        errors.append(f"✨ Row {index+1}: New drug '{brand_name}' identified and added to database.")
                    else:
                        errors.append(f"❌ Row {index+1}: '{brand_name}' is not recognized as a valid medicine by AI.")
                        continue
                except Exception as e:
                    print(f"AI Lookup failed: {e}")
                    errors.append(f"❌ Row {index+1}: AI lookup failed for '{brand_name}'.")
                    continue

            if not drug:
                errors.append(f"❌ Row {index+1}: Drug '{brand_name}' not found (even with fuzzy matching).")
                continue
                
            # Check if batch exists
            existing_batch = session.query(InventoryBatch).filter_by(batch_number=batch_number).first()
            
            if existing_batch:
                existing_batch.quantity += quantity
            else:
                new_batch = InventoryBatch(
                    batch_id=f"BATCH-{batch_number}-{datetime.now().strftime('%Y%m%d%H%M%S')}", # Generate unique ID
                    drug_id=drug.drug_id,
                    batch_number=batch_number,
                    quantity=quantity,
                    purchase_price=0.0, # Default or add column
                    sell_price=0.0, # Default or add column
                    expiry_date=expiry_date,
                    supplier_id="SUP001", # Default or add column logic
                    location=location
                )
                session.add(new_batch)
            
            added_count += 1
            
        session.commit()
        
        message = f"Successfully processed {added_count} items."
        if errors:
            message += f"\nErrors encountered:\n" + "\n".join(errors[:5])
            if len(errors) > 5:
                message += f"\n...and {len(errors)-5} more errors."
                
        return {"message": message, "added_count": added_count, "errors": errors}
        
    except Exception as e:
        session.rollback()
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")
    finally:
        session.close()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
