ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - prisma
